"""
Demo Cache — Pre-built responses for instant demo showcases.
"""


def get_cached_response(query: str) -> dict | None:
    query_lower = query.lower().strip()
    for keywords, response in DEMO_CACHE.items():
        if any(kw in query_lower for kw in keywords):
            return response
    return None


DEMO_CACHE = {
    ("fourier", "fourier transform"): {
        "explanation": "The **Fourier Transform** is one of the most powerful tools in mathematics and engineering. Think of it as a magical prism for signals.\n\n**The Core Idea:** Just like a glass prism splits white light into a rainbow of individual colors, the Fourier Transform takes any complex signal and breaks it down into simple sine waves of different frequencies.\n\n**A Simple Analogy:** Imagine you're listening to a symphony orchestra. Your ears hear one combined sound, but a Fourier Transform is like having the ability to instantly separate that single sound into every individual instrument playing.\n\n**Why It Matters:**\n- **Audio Processing**: Spotify uses it to compress music\n- **Image Processing**: JPEG compression uses a variant (DCT)\n- **Medical Imaging**: MRI machines use Fourier Transforms\n- **Telecommunications**: Your phone uses it constantly\n\n**Key Insight:** Any signal, no matter how complicated, can be represented as a sum of simple sine and cosine waves.",
        "math": "### Step-by-Step Mathematical Derivation\n\n**Step 1: Define the Continuous Fourier Transform**\n\n$$F(\\omega) = \\int_{-\\infty}^{\\infty} f(t) \\cdot e^{-j\\omega t} \\, dt$$\n\nwhere $F(\\omega)$ = frequency-domain representation, $f(t)$ = time-domain signal, $\\omega = 2\\pi f$ = angular frequency.\n\n**Step 2: Euler's Formula**\n\n$e^{-j\\omega t} = \\cos(\\omega t) - j\\sin(\\omega t)$\n\nThe transform computes correlation between $f(t)$ and sinusoids of every frequency.\n\n**Step 3: Inverse Transform**\n\n$$f(t) = \\frac{1}{2\\pi} \\int_{-\\infty}^{\\infty} F(\\omega) \\cdot e^{j\\omega t} \\, d\\omega$$\n\n**Step 4: Key Properties**\n- **Linearity**: $\\mathcal{F}\\{af + bg\\} = aF + bG$\n- **Convolution Theorem**: $\\mathcal{F}\\{f * g\\} = F \\cdot G$\n\n**Step 5: DFT** for N samples: $X[k] = \\sum_{n=0}^{N-1} x[n] \\cdot e^{-j2\\pi kn/N}$",
        "visual_text": "### Visual Representation: Fourier Transform\n\n```\nTIME DOMAIN                    FREQUENCY DOMAIN\nAmplitude                      Magnitude\n  |   /\\  /\\  /\\                 |\n  |  /  \\/  \\/  \\  == FT ==>    |  ||\n  | /              \\             |  ||  ||\n  |/                \\            |  ||  ||  ||\n  +-------------------->         +--||--||--||-->\n       Time (t)                   Frequency\n```\n\n**Key Elements:**\n- Left: complex wave in time domain\n- Right: frequency spectrum (bars = frequency strengths)\n- Arrow: Fourier Transform operation",
        "visual_image": None,
        "synthesized": "Here's your comprehensive study guide on the **Fourier Transform**.\n\n## 📖 Simple Explanation\n\nThe Fourier Transform is a **mathematical prism**. Just as a prism splits white light into colors, it breaks any signal into simple sine waves. When you hear a chord, the FT can identify every individual note and how loud each one is.\n\n**Uses:** Audio compression (MP3), image compression (JPEG), medical imaging (MRI), and telecommunications.\n\n## 🔢 Mathematical Insight\n\n$$F(\\omega) = \\int_{-\\infty}^{\\infty} f(t) \\cdot e^{-j\\omega t} \\, dt$$\n\n1. Start with signal $f(t)$ in time domain\n2. Multiply by $e^{-j\\omega t}$ to test each frequency\n3. Integrate over all time to get that frequency's contribution\n4. Key property: Convolution in time = multiplication in frequency\n\n## 🎨 Visual Understanding\n\n```\nTIME DOMAIN          =>  FT  =>          FREQUENCY DOMAIN\n~~~complex wave~~~                        ||bars for each freq||\n```\n\nThe signal on the left transforms into a bar chart on the right, where each bar represents a frequency component's strength.\n\n---\n\n💡 **Key Takeaway:** The Fourier Transform reveals the hidden frequency recipe of any signal.",
    },
    ("newton", "newton's laws", "laws of motion"): {
        "explanation": "**Newton's Laws of Motion** are three fundamental rules that describe how objects move.\n\n**First Law (Inertia):** An object at rest stays at rest, and an object in motion keeps moving — unless acted on by an outside force. Like a hockey puck on ice.\n\n**Second Law (F = ma):** Acceleration depends on net force and mass. More force = more acceleration. More mass = less acceleration. Easier to push an empty cart than a full one.\n\n**Third Law (Action-Reaction):** Every action has an equal and opposite reaction. Push a wall, it pushes back. Rocket expels gas down, gas pushes rocket up.",
        "math": "### Step-by-Step Derivation\n\n**Step 1:** $\\vec{F}_{net} = m\\vec{a}$\n\n**Step 2:** Since $\\vec{a} = d\\vec{v}/dt$: $\\vec{F} = m \\frac{d\\vec{v}}{dt}$\n\n**Step 3:** Momentum $\\vec{p} = m\\vec{v}$, so $\\vec{F} = \\frac{d\\vec{p}}{dt}$\n\n**Step 4:** First Law: When $F=0$, $dv/dt = 0$, so $v = $ constant\n\n**Step 5:** Third Law: $\\vec{F}_{A→B} = -\\vec{F}_{B→A}$\n\n**Step 6:** Free fall: $F = mg = ma$, so $a = g = 9.8$ m/s²",
        "visual_text": "### Visual: Newton's Laws\n\n```\nFIRST LAW:   ●------> ●------> (keeps moving)\nSECOND LAW:  F--> [████] -> small a (big mass)\n             F=====> [██] -> BIG A (small mass)\nTHIRD LAW:   <--F-- 🧑 --F--> 🧱 (action=reaction)\n```",
        "visual_image": None,
        "synthesized": "## 📖 Simple Explanation\n\n**1st Law:** Objects resist change. No force = no change in motion.\n**2nd Law:** $F = ma$. More force = more acceleration; more mass = less acceleration.\n**3rd Law:** Forces come in pairs. Push something, it pushes back equally.\n\n## 🔢 Mathematical Insight\n\nCore equation: $\\vec{F} = m\\vec{a} = \\frac{d\\vec{p}}{dt}$\n\n- 1st Law is when $F = 0 \\Rightarrow v = $ constant\n- 3rd Law: $\\vec{F}_{A→B} = -\\vec{F}_{B→A}$\n\n## 🎨 Visual Understanding\n\n```\n1st: ●----->  (keeps moving, no force needed)\n2nd: Big force + small mass = BIG acceleration\n3rd: <--F-- 🧑 --F--> 🧱\n```\n\n💡 **Key Takeaway:** $F = ma$ is the master equation — the other two laws are its special cases.",
    },
    ("neural network", "neural net", "deep learning"): {
        "explanation": "**Neural Networks** are computing systems inspired by the brain — the engine behind modern AI.\n\n**Core Idea:** A neural network is a series of connected layers that learn to transform inputs into outputs, like an assembly line where raw data goes in and predictions come out.\n\n**Analogy:** Teaching a child to recognize cats — show thousands of photos, correct mistakes, and they learn patterns. Neural nets do this with math.\n\n**Key Components:**\n- **Neurons**: Process inputs with weights and activation functions\n- **Layers**: Input → Hidden → Output\n- **Training**: Show examples, compute error, adjust weights via backpropagation",
        "math": "### Step-by-Step Derivation\n\n**Step 1:** Neuron: $z = \\vec{w} \\cdot \\vec{x} + b$\n\n**Step 2:** Activation: $a = \\sigma(z)$ (ReLU, Sigmoid, etc.)\n\n**Step 3:** Layer: $Z^{[l]} = W^{[l]}A^{[l-1]} + b^{[l]}$, $A^{[l]} = \\sigma(Z^{[l]})$\n\n**Step 4:** Loss: $\\mathcal{L} = -\\frac{1}{m}\\sum[y\\log\\hat{y} + (1-y)\\log(1-\\hat{y})]$\n\n**Step 5:** Backprop: $\\frac{\\partial\\mathcal{L}}{\\partial W^{[l]}} = \\frac{1}{m}\\delta^{[l]}(A^{[l-1]})^T$\n\n**Step 6:** Update: $W := W - \\alpha \\frac{\\partial\\mathcal{L}}{\\partial W}$",
        "visual_text": "### Visual: Neural Network\n\n```\nINPUT    HIDDEN    OUTPUT\n ●--------●\n  \\      / \\\n   ●----●   ●----● (prediction)\n  /      \\ /\n ●--------●\n```\n\nTraining Loop:\n```\nInput -> Forward Pass -> Loss -> Backprop -> Update Weights\n  ^                                              |\n  +-------------- Repeat N epochs ---------------+\n```",
        "visual_image": None,
        "synthesized": "## 📖 Simple Explanation\n\nA neural network is a **learning factory**. Data enters, passes through processing layers, and predictions come out. It improves by adjusting internal weights each time it makes a mistake.\n\n## 🔢 Mathematical Insight\n\nEach neuron: $a = \\sigma(\\vec{w}\\cdot\\vec{x} + b)$\n\nTraining: Forward pass → Compute loss → Backpropagate gradients → Update weights\n\n$$W := W - \\alpha \\frac{\\partial\\mathcal{L}}{\\partial W}$$\n\n## 🎨 Visual Understanding\n\n```\n●--●\n \\/ \\\n●--●--● (prediction)\n /\\ /\n●--●\n```\n\nPredict → Measure error → Adjust → Repeat\n\n💡 **Key Takeaway:** Neural networks learn by example through backpropagation — no explicit programming required.",
    },
}
