services:
  - type: web
    name: trimind
    env: docker
    plan: free
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CF_WORKER_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
